### ISSUE TITLE
Which class in the rdnet.py file in the rdnet folder is the transition layer

### ISSUE THREAD

**Issue by sevendiv-happy** [naver-ai/rdnet#12]
Which class in the rdnet.py file in the rdnet folder is the transition layer

**Comment by dhkim0225** [comment]
The following lines imply the transition layer.
https://github.com/naver-ai/rdnet/blob/6739093bf0af0ec53af163ff15e91d46d66dbe9e/rdnet/rdnet.py#L211-L214

**Comment by DennisInTw** [comment]
Hello, 
I have the similar question, too.
It describes there are more transition layers, which are not only after each stage, but after every three blocks.
But I can only find out the transition layer you pointed out (i.e. before three DenseBlock).

Could you please help give some advise?
Thanks.

**Comment by dhkim0225** [comment]
@DennisInTw Thank you for your interest in our work.

For a cleaner implementation, I implement RDNets with **more stages** rather than just 4 stages. 

As seen in the following code block (https://github.com/naver-ai/rdnet/blob/6739093bf0af0ec53af163ff15e91d46d66dbe9e/rdnet/rdnet.py#L378-L387), the RDNet base is composed of 11 stages. 

Through "is_downsample_block" argument, stages that do not downsample can be configured.

**Comment by DennisInTw** [comment]
Thanks for your kindly help!
