### ISSUE TITLE
Robust test

### ISSUE THREAD

**Issue by LMMMEng** [naver-ai/rdnet#13]
Thank you for your solid work.

Could you please provide the code of the robustness test? Thanks a lot!

**Comment by dhkim0225** [comment]
Thank you for your interest!

There is a "robustness evaluation tool" commonly used within our company. 
Due to company policies, it seems difficult to share it.

**Comment by dyhan0920** [comment]
@LMMMEng Thank you very much for your interest.

Since we used the internal code (including PyTorch dataloaders for the ImageNet variants) for robustness evaluations, the benchmark code is almost equivalent to a publicly released code like [Model Soup](https://github.com/mlfoundations/model-soups).

Let me provide an easy-to-use Jupyter notebook code [here](https://github.com/naver-ai/model-stock/blob/main/notebooks/model_stock_eval.ipynb) for robustness benchmark that can be run standalone as well.

We will be including the robustness benchmark in this repository.

**Comment by LMMMEng** [comment]
@dyhan0920 Thanks a lot! It's quite helpful.
