### ISSUE TITLE
Where can I find the CIFAR-10 training code?

### ISSUE THREAD

**Issue by 181404010226** [naver-ai/rdnet#2]
I discovered this repository through the "Papers with Code" page for CIFAR-10 image classification. However, it appears that this repository primarily addresses the ImageNet dataset. Could you provide the CIFAR-10 training code to assist with my research?Thanks.

**Comment by dyhan0920** [comment]
Thank you for your interests in our work. [timm](https://github.com/huggingface/pytorch-image-models) was used for CIFAR-10 fine-tuning training like the ImageNet-pretraining. 

I believe any other training code, such as the code in torchvision, would work for fine-tuning with the provided pre-trained model because data augmentations were not employed during training.

**Comment by dyhan0920** [comment]
Thank you for your interest in our work. [timm](https://github.com/huggingface/pytorch-image-models) was used for CIFAR-10 fine-tuning training like the ImageNet-pretraining. 

I believe any other training code, such as the code in TorchVision, would work for fine-tuning with the provided pre-trained model because data augmentations were barely employed during training, similar to how [DeiT](https://github.com/facebookresearch/deit) did it.
